from typing import Dict, List, Callable

class OSDInfo(object):
    def __init__(self, id: int, journal: str = None, storage: str = None) -> None: ...

def get_osds_nodes(rpc_run: Callable[[str], str], extra_args: str = "") -> Dict[str, List[OSDInfo]]: ...
def get_mons_nodes(rpc_run: Callable[[str], str], extra_args: str = "") -> Dict[int, str]: ...
